void SystemInitializeSound(void);
void SystemUpdateSound(void);
void SystemSuspendSound(void);
void SystemResumeSound(void);
extern u8* soundRequest[4];
extern u8* soundHead[4];
extern u8* soundPlay[4];
extern u8 const mmlNull[];
extern u8 const mmlTitleStartChannel0[];
extern u8 const mmlTitleStartChannel1[];
extern u8 const mmlTitleStartChannel2[];
extern u8 const mmlStartChannel0[];
extern u8 const mmlStartChannel1[];
extern u8 const mmlStartChannel2[];
extern u8 const mmlHiScoreChannel0[];
extern u8 const mmlHiScoreChannel1[];
extern u8 const mmlHiScoreChannel2[];
extern u8 const mmlShotChannel0[];
extern u8 const mmlBombChannel0[];
extern u8 const mmlEnemyTurnChannel1[];
extern u8 const mmlEnemyBombChannel2[];
